version: '3.8'
services:
    post-service:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8000:8000
        volumes:
            - .:/app
        command: 'php artisan serve --host=0.0.0.0'
